#!/usr/bin/env python
"""Evaluate a (trained) model on a MolecularIQ question dataset with vLLM.

Works against:
  * datasets generated by scripts/create_datasets.py (e.g. data/count/val.jsonl)
  * the official benchmark: --dataset ml-jku/moleculariq-v0.0 --split single_count

Scoring uses the official extraction function + symbolic verifier — identical
to the training reward and the official harness. Reports avg_accuracy,
pass@1 / pass@k (with --n > 1), plus per-feature and per-complexity breakdowns.

Examples
--------
# Held-out questions of our generated dataset (greedy, pass@1):
python scripts/evaluate.py --model outputs/count-qwen2.5-0.5b \
    --dataset data/count/val.jsonl --out results/count_val.json

# Official benchmark split, sampled pass@3 like the paper protocol:
python scripts/evaluate.py --model outputs/count-qwen2.5-0.5b \
    --dataset ml-jku/moleculariq-v0.0 --split single_count \
    --n 3 --temperature 1.0 --out results/count_official.json

# Baseline comparison (untrained model):
python scripts/evaluate.py --model Qwen/Qwen2.5-0.5B-Instruct \
    --dataset data/count/val.jsonl --out results/count_val_baseline.json
"""
import argparse
import json
import logging
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from moleculariq_grpo.extraction import extract_moleculariq_answer  # noqa: E402
from moleculariq_grpo.prompts import SYSTEM_PROMPT, build_prompt  # noqa: E402
from moleculariq_grpo.rewards import score_answer  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("evaluate")


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", required=True, help="HF model name or local checkpoint dir")
    p.add_argument("--dataset", required=True,
                   help="Path to a .jsonl file, a dataset dir (uses --split .jsonl), "
                        "or an HF dataset id (e.g. ml-jku/moleculariq-v0.0)")
    p.add_argument("--split", default="val",
                   help="Split name (for dataset dirs and HF datasets). "
                        "Official splits: test, single_count, multi_count, single_index, "
                        "multi_index, single_constraint_generation, multi_constraint_generation")
    p.add_argument("--features", nargs="+", default=None,
                   help="Only evaluate rows whose 'features' value is in this list "
                        "(e.g. single_count_aromatic_ring)")
    p.add_argument("--limit", type=int, default=None, help="Evaluate at most N questions")
    p.add_argument("--n", type=int, default=1, help="Samples per question (pass@k)")
    p.add_argument("--temperature", type=float, default=0.0,
                   help="0.0 = greedy (default). Official pass@3 protocol samples with "
                        "do_sample; use --n 3 --temperature 1.0 for comparable numbers.")
    p.add_argument("--top-p", type=float, default=1.0)
    p.add_argument("--max-tokens", type=int, default=1024)
    p.add_argument("--max-model-len", type=int, default=4096)
    p.add_argument("--gpu-mem-util", type=float, default=0.85)
    p.add_argument("--tensor-parallel", type=int, default=1)
    p.add_argument("--dtype", default="bfloat16")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", type=Path, required=True, help="Output results JSON path")
    p.add_argument("--dump-samples", action="store_true",
                   help="Also write per-sample generations next to --out")
    return p.parse_args()


def load_rows(args) -> list[dict]:
    ds_arg = args.dataset
    path = Path(ds_arg)
    if path.is_file():
        rows = [json.loads(l) for l in path.open() if l.strip()]
    elif path.is_dir():
        f = path / f"{args.split}.jsonl"
        if not f.exists():
            raise SystemExit(f"{f} not found")
        rows = [json.loads(l) for l in f.open() if l.strip()]
    else:
        from datasets import load_dataset
        ds = load_dataset(ds_arg, split=args.split)
        rows = [dict(r) for r in ds]

    if args.features:
        allowed = set(args.features)
        rows = [r for r in rows if r.get("features") in allowed]
        if not rows:
            raise SystemExit(f"No rows with features in {sorted(allowed)}")
    if args.limit:
        rows = rows[: args.limit]
    return rows


def pass_at_k(rewards: list[float], k: int) -> float:
    return float(any(r > 0 for r in rewards[:k]))


def main():
    args = parse_args()
    rows = load_rows(args)
    logger.info("Evaluating %s on %d questions (%s, split=%s, n=%d, T=%g)",
                args.model, len(rows), args.dataset, args.split, args.n, args.temperature)

    from transformers import AutoTokenizer
    from vllm import LLM, SamplingParams

    tokenizer = AutoTokenizer.from_pretrained(args.model)
    prompts = [
        tokenizer.apply_chat_template(
            build_prompt(r["question"], SYSTEM_PROMPT),
            tokenize=False,
            add_generation_prompt=True,
        )
        for r in rows
    ]

    llm = LLM(
        model=args.model,
        dtype=args.dtype,
        max_model_len=args.max_model_len,
        gpu_memory_utilization=args.gpu_mem_util,
        tensor_parallel_size=args.tensor_parallel,
        seed=args.seed,
    )
    sampling = SamplingParams(
        n=args.n,
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        seed=args.seed,
    )
    outputs = llm.generate(prompts, sampling)

    per_question = []
    metrics_acc = []
    by_features = defaultdict(list)
    by_bin = defaultdict(list)
    by_task = defaultdict(list)

    for row, out in zip(rows, outputs):
        texts = [o.text for o in out.outputs]
        rewards = [
            score_answer(t, row.get("task_type"),
                         target=row.get("target"),
                         constraints=row.get("constraints"))
            for t in texts
        ]
        q_avg = sum(rewards) / len(rewards)
        metrics_acc.append(q_avg)
        by_features[row.get("features", "unknown")].append(q_avg)
        by_bin[row.get("complexity_bin", "unknown")].append(q_avg)
        by_task[row.get("task_type", "unknown")].append(q_avg)
        per_question.append({
            "uid": row.get("uid"),
            "features": row.get("features"),
            "rewards": rewards,
            "responses": texts if args.dump_samples else None,
            "extracted": [str(extract_moleculariq_answer(t))[:300] for t in texts],
        })

    n_q = len(rows)
    results = {
        "model": args.model,
        "dataset": args.dataset,
        "split": args.split,
        "features_filter": args.features,
        "num_questions": n_q,
        "n_samples_per_question": args.n,
        "temperature": args.temperature,
        "top_p": args.top_p,
        "max_tokens": args.max_tokens,
        "avg_accuracy": sum(metrics_acc) / n_q,
        "pass_at_1": sum(pass_at_k(p["rewards"], 1) for p in per_question) / n_q,
        "by_task_type": {k: sum(v) / len(v) for k, v in sorted(by_task.items())},
        "by_features": {k: sum(v) / len(v) for k, v in sorted(by_features.items())},
        "by_complexity_bin": {k: sum(v) / len(v) for k, v in sorted(by_bin.items())},
    }
    if args.n >= 3:
        results["pass_at_3"] = sum(pass_at_k(p["rewards"], 3) for p in per_question) / n_q
    if args.n >= 5:
        results["pass_at_5"] = sum(pass_at_k(p["rewards"], 5) for p in per_question) / n_q

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(results, f, indent=2)

    samples_path = args.out.with_suffix(".samples.jsonl")
    with open(samples_path, "w") as f:
        for p in per_question:
            f.write(json.dumps(p) + "\n")

    logger.info("Results: avg_accuracy=%.4f pass@1=%.4f%s",
                results["avg_accuracy"], results["pass_at_1"],
                f" pass@3={results['pass_at_3']:.4f}" if "pass_at_3" in results else "")
    logger.info("Per task type: %s", results["by_task_type"])
    logger.info("Wrote %s (per-sample: %s)", args.out, samples_path)


if __name__ == "__main__":
    main()
